# Generated by Django 5.2.3 on 2025-07-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название произведения')),
                ('author', models.CharField(max_length=255, verbose_name='Автор произведения')),
            ],
            options={
                'verbose_name': 'произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Цитата из фильма или книги', verbose_name='Цитата')),
                ('value', models.IntegerField(help_text='Чем выше вес, тем больше шанс выдачи этой\n         цитаты на заглавной странице', verbose_name='Вес цитаты')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Количество дизлайков')),
                ('source', models.ForeignKey(help_text='Источник цитаты', on_delete=django.db.models.deletion.CASCADE, related_name='masterpieces', to='page.masterpiece', verbose_name='Произведение')),
            ],
            options={
                'verbose_name': 'цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ('-likes',),
                'constraints': [models.UniqueConstraint(fields=('content', 'source'), name='Unique quote constraint')],
            },
        ),
    ]
