# Generated by Django 5.2.3 on 2025-07-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.masterpiece'),
        ),
    ]
