# Generated by Django 5.2.3 on 2025-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_masterpiece_alter_quote_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('content', 'source'), name='Unique quote constraint'),
        ),
    ]
