# Generated by Django 5.2.3 on 2025-07-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_quote_unique_quote_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterpieces', to='page.masterpiece'),
        ),
    ]
