# Generated by Django 5.2.3 on 2025-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_quote_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
