# Generated by Django 5.2.3 on 2025-07-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_quote_dislikes_quote_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-likes',)},
        ),
    ]
