# Generated by Django 5.2.3 on 2025-07-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_quote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterpiece',
            options={'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-likes',), 'verbose_name': 'цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterField(
            model_name='masterpiece',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор произведения'),
        ),
        migrations.AlterField(
            model_name='masterpiece',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(help_text='Цитата из фильма или книги', verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(help_text='Источник цитаты', on_delete=django.db.models.deletion.CASCADE, related_name='masterpieces', to='page.masterpiece', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='value',
            field=models.IntegerField(help_text='Чем выше вес, тем больше шанс выдачи этой цитаты на заглавной странице', verbose_name='Вес цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
